# ### NOCTALIA ###
# Apps
$clipboard = qs -c noctalia-shell ipc call plugin:clipper toggle

# System
$launcher = qs -c noctalia-shell ipc call launcher toggle
$cCenter = qs -c noctalia-shell ipc call controlCenter toggle
$settings = qs -c noctalia-shell ipc call settings toggle
$session = qs -c noctalia-shell ipc call sessionMenu toggle

# Audio management
$volUp = qs -c noctalia-shell ipc call volume increase
$volDown = qs -c noctalia-shell ipc call volume decrease
$muteOut = qs -c noctalia-shell ipc call volume muteOutput
$muteIn = qs -c noctalia-shell ipc call volume muteInput

# Media controls
$pPause = qs -c noctalia-shell ipc call media playPause
$next = qs -c noctalia-shell ipc call media next
$previous = qs -c noctalia-shell ipc call media previous

# Screen recorder
$rec = qs -c noctalia-shell ipc call plugin:screen-shot-and-record record
$recSound = qs -c noctalia-shell ipc call plugin:screen-shot-and-record recordsound

# Screenshot
$screenshot = qs -c noctalia-shell ipc call plugin:screen-shot-and-record screenshot

# Text Recognition & Google Lens
$text = qs -c noctalia-shell ipc call plugin:screen-shot-and-record ocr
$lens = qs -c noctalia-shell ipc call plugin:screen-shot-and-record search

# Assistant Panel 
$ai = qs -c noctalia-shell ipc call plugin:assistant-panel toggle

# ### BASIC APPS ###
$terminal = kitty
$browser = zen-browser
$fileManager = ~/.local/bin/yazi.sh
$mediaPlayer = ~/.local/bin/rmpc.sh

