# ### XDG stuff ###
env = XDG_CURRENT_DESKTOP, Hyprland
env = XDG_SESSION_TYPE, wayland
env = XDG_SESSION_DESKTOP, Hyprland

# ### Theming ###
env = QT_QPA_PLATFORMTHEME, qt6ct
env = HYPRCURSOR_THEME, AC-Future
env = HYPRCURSOR_SIZE, 40

# ### IDK ###
env = ELECTRON_OZONE_PLATFORM_HINT, auto
