input {
        kb_layout = us
        kb_variant = intl
        kb_options = shift:both_capslock, compose:caps
        numlock_by_default = true
        repeat_delay = 250
        repeat_rate = 35
}
