source = $hypr/variables.conf

# ### NOCTALIA ###
# Core binds
bind = SUPER, Space, exec, $launcher	# Opens the app launcher
bind = SUPER, period, exec, $cCenter	# Opens the control center
bind = SUPER, comma, exec, $settings	# Opens the settings

# Utility binds
bind = SUPER, V, exec, $clipboard		# Opens the clipboard
bind = , XF86Calculator, exec, $launcher	# Opens the launcher (calculator key)
bind = Ctrl+Alt, Delete, exec, $session		# Logout, reboot, shutdown...

# Audio controls
bindel = , XF86AudioRaiseVolume, exec, $volUp	   # Volume up key
bindel = , XF86AudioLowerVolume, exec, $volDown	   # Volume down key
bindl = , XF86AudioMute, exec, $muteOut      	   # Mute audio key
bindl = SUPER, Z, exec, $muteIn			   # Mute input

# Media controls
bindl = , F3, exec, $pPause 	# Play / Pause media
bindl = , F4, exec, $next 	# Next media track 
bindl = , F2, exec, $previous 	# Previous media track

# Screen recorder
bindl = SUPER, BackSpace, exec, $rec			# Start / stop the screen recording
bindl = SUPER+Shift, BackSpace, exec, $recSound		# Screen recording with sound

# Screenshot
bind = , PRINT, exec, $screenshot	# Left-click copy to clipboard, right-click opens editor

# Assistant Panel
bind = SUPER, A, exec, $ai	# Opens Assistant Panel

# Text Recognition & Google Lens 
bindl = SUPER, semicolon, exec, $text
bindl = SUPER, dead_acute, exec, $lens

# ToDo List
bind = SUPER, G, exec, $todo

# Hyprland Workspaces 
bind = SUPER, Tab, exec, qs -c noctalia-shell ipc call plugin:workspace-overview toggle

# ### HYPRLAND ###
# Window actions
bind = SUPER, Q, killactive			# Kills active window

bind = SUPER, left, movefocus, l		# Focus on the window to the left
bind = SUPER, right, movefocus, r		# Focus on the window to the right
bind = SUPER, up, movefocus, u			# Focus on the window above
bind = SUPER, down, movefocus, d		# Focus on the window below

bind = SUPER+Shift, left, movewindow, l		# Moves window to the left
bind = SUPER+Shift, right, movewindow, r	# Moves window to the right
bind = SUPER+Shift, up, movewindow, u		# Moves window up
bind = SUPER+Shift, down, movewindow, d		# Moves window down

bind = CTRL+Shift, left, layoutmsg, swapcol l	# (Scrolling) Swaps window to the left
bind = CTRL+Shift, right, layoutmsg, swapcol r	# (Scrolling) Swaps window to the right

bind = CTRL, left, workspace, e-1
bind = CTRL, right, workspace, e+1
bind = SUPER+CTRL, left, workspace, -1
bind = SUPER+CTRL, right, workspace, +1

bindm = SUPER, mouse:272, movewindow		# SUPER + LMB: Moves a window by dragging it more than 10px
bindm = SUPER, mouse:273, resizewindow 1	# SUPER + RMB: Resizes a window
bindc = SUPER, mouse:272, togglefloating	# SUPER + LMB: Floats a window by clicking it

bind = SUPER, R, layoutmsg, colresize +conf	# (Scrolling) Cycles between column width presets

bind = SUPER, F, fullscreen, 1 			# Fullscreens the window
bind = SUPER+Shift, F, fullscreen, 0		# Maximizes the window

# Workspace actions
bind = SUPER, D, togglespecialworkspace, dev
bind = SUPER, C, togglespecialworkspace, chat

# Apps shortcuts
bind = SUPER, T, exec, $terminal	# Opens the terminal
bind = SUPER, W, exec, $browser		# Opens the browser
bind = SUPER, E, exec, $fileManager	# Opens the file manager
bind = SUPER, M, exec, $mediaPlayer

