source = $hypr/variables.conf

# ### NOCTALIA ###
# Core binds
bind = SUPER, Space, exec, $launcher	# Opens the app launcher
bind = SUPER, period, exec, $cCenter	# Opens the control center
bind = SUPER, comma, exec, $settings	# Opens the settings

# Utility binds
bind = SUPER, V, exec, $clipboard		    # Opens the clipboard
bind = , XF86Calculator, exec, $launcher	# Opens the launcher (calculator key)
bind = Ctrl+Alt, Delete, exec, $session		# Logout, reboot, shutdown...

# Audio controls
bindel = , XF86AudioRaiseVolume, exec, $volUp	    # Volume up key
bindel = , XF86AudioLowerVolume, exec, $volDown	    # Volume down key
bindl = , XF86AudioMute, exec, $muteOut      	    # Mute audio key
bindl = SUPER, Z, exec, $muteIn                     # Mute input

# Media controls
bindl = , F3, exec, $pPause 	# Play / Pause media
bindl = , F4, exec, $next 	    # Next media track 
bindl = , F2, exec, $previous 	# Previous media track

# Screen recorder
bindl = SUPER, BackSpace, exec, $rec    			# Start / stop the screen recording
bindl = SUPER+Shift, BackSpace, exec, $recSound		# Screen recording with sound

# Screenshot
bind = , PRINT, exec, $screenshot	# Left-click copy to clipboard, right-click opens editor

# Text Recognition & Google Lens 
bindl = SUPER, semicolon, exec, $text
bindl = SUPER, dead_acute, exec, $lens

# ToDo List
bind = SUPER, G, exec, $todo

# Hyprland Workspaces 
bind = SUPER, Tab, exec, qs -c noctalia-shell ipc call plugin:workspace-overview toggle

# ### HYPRLAND ###
# Window actions
bind = SUPER, Q, killactive			# Kills active window

bind = SUPER, left, layoutmsg, move -col		# Moves the layout 1col to the left
bind = SUPER, right, layoutmsg, move +col		# Moves the layoyt 1col to the right
bind = SUPER, up, layoutmsg, move +col			# '' (for vertical monitor)
bind = SUPER, down, layoutmsg, move -col		# '' (for vertical monitor)

bind = SUPER+Shift, left, layoutmsg, swapcol l		# Swaps window to the left
bind = SUPER+Shift, right, layoutmsg, swapcol r		# Swaps window to the right
bind = SUPER+Shift, up, swapwindow, u               # Swaps window up
bind = SUPER+Shift, down, swapwindow, d             # Swaps window down

bindm = SUPER, mouse:272, movewindow		    # SUPER + LMB: Moves a window by dragging it more than 10px
bindm = SUPER, mouse:273, resizewindow 1	    # SUPER + RMB: Resizes a window
bindc = SUPER, mouse:272, togglefloating	    # SUPER + LMB: Floats a window by clicking it

bind = SUPER, R, layoutmsg, colresize +conf	    # (Scrolling) Cycles between column width presets

bind = SUPER+Shift, F, fullscreenstate, 2 2 toggle			# Fullscreens the window
bind = SUPER, F, fullscreenstate, 1 1 toggle        	    # Maximizes the window

# Workspace actions
bind = SUPER, D, togglespecialworkspace, dev
bind = SUPER, C, togglespecialworkspace, chat

bind = CTRL, left, workspace, e-1                   # Open workspace -1
bind = CTRL, right, workspace, e+1                  # Open workspace +2
bind = CTRL+Shift, right, movetoworkspace, e+1      # Moves window to open workspace +1
bind = CTRL+Shift, left, movetoworkspace, e-1       # Moves window to open workspace -1
bind = SUPER+Alt, left, workspace, -1               # Workspace -1
bind = SUPER+Alt, right, workspace, +1              # Workspace +1

bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8

# Apps shortcuts
bind = SUPER, T, exec, $terminal	    # Opens the terminal
bind = SUPER, W, exec, $browser		    # Opens the browser
bind = SUPER, E, exec, $fileManager	    # Opens the file manager
bind = SUPER, M, exec, $mediaPlayer     # Opens the media player

