# ### FLOATIES ###
windowrule = match:title terminal filechooser, size 800 500, float on, center on
windowrule = match:title arch-update, size 800 500, float on, center on
windowrule = match:class rmpc, size 1000 500, float on, move (monitor_w*0.24) (monitor_h*0.53)
windowrule = match:class yazi, size 800 600, float on, move (monitor_w*0.3) (monitor_h*0.045)
windowrule = match:title .*Friends.*, float on, center on

windowrule = match:title .*Sign in.*, center on

# ### SPECIAL WORKSPACES ###
# Development
windowrule = match:title .*GitHub.*, workspace special:dev silent 

# Chat
windowrule = match:title .*WhatsApp.*, workspace special:chat silent
windowrule = match:class equibop, workspace special:chat silent

# ### DEFINED WORKSPACES ###
windowrule = match:class libresprite, workspace name: 
windowrule = match:class .*inkscape.*, workspace name:

windowrule = match:class steam, workspace name:󰊖     
