# ### FLOATIES ###
windowrule = match:title terminal filechooser, size 800 500, float on, center on
windowrule = match:title arch-update, size 800 500, float on, center on

# RMPC HDMI-A-1
windowrule = match:class rmpc, match:workspace m[HDMI-A-1], size 1000 500, float on, move (monitor_w*0.24) (monitor_h*0.53)
windowrule = match:class rmpc, match:workspace m[HDMI-A-1] s[true], size 1000 500, float on, move (monitor_w*0.24) (monitor_h*0.53)
# RMPC DP-1
windowrule = match:class rmpc, match:workspace m[DP-1], size 1000 500, float on, move (monitor_w*0.04) (monitor_h*0.74)
windowrule = match:class rmpc, match:workspace m[DP-1] s[true], size 1000 500, float on, move (monitor_w*0.04) (monitor_h*0.74)

# Yazi HDMI-A-1
windowrule = match:class yazi, match:workspace m[HDMI-A-1], size 900 600, float on, move (monitor_w*0.3) (monitor_h*0.045)
windowrule = match:class yazi, match:workspace m[HDMI-A-1] s[true], size 900 600, float on, move (monitor_w*0.3) (monitor_h*0.045)
# Yazi DP-1
windowrule = match:class yazi, match:workspace m[DP-1], size 900 600, float on, move (monitor_w*0.13) (monitor_h*0.026)
windowrule = match:class yazi, match:workspace m[DP-1] s[true], size 900 600, float on, move (monitor_w*0.13) (monitor_h*0.026)

# Steam
windowrule = match:title .*Friends.*, float on, center on
windowrule = match:title .*Sign in.*, center on


# ### SPECIAL WORKSPACES ###
# Development
windowrule = match:title .*GitHub.*, workspace special:dev silent 
windowrule = match:title .*kitty-dev.*, workspace special:dev silent

# Chat
windowrule = match:title .*WhatsApp.*, workspace special:chat silent
windowrule = match:class equibop, workspace special:chat silent

# ### DEFINED WORKSPACES ###
windowrule = match:class libresprite, workspace name:
windowrule = match:class .*inkscape.*, workspace name:
windowrule = match:class steam, workspace name:󰊖
