workspace = 1, defaultName:, monitor:HDMI-A-1
workspace = 2, defaultName:, monitor:HDMI-A-1
workspace = 3, defaultName:, monitor:HDMI-A-1
workspace = 4, monitor:HDMI-A-1, default:true, persistent:true
workspace = 5, defaultName:, monitor:DP-1
workspace = 6, monitor:DP-1, default:true, persistent:true
workspace = 7, monitor:DP-1
workspace = 8, monitor:DP-1

workspace = m[DP-1], layoutopt:direction:up
workspace = m[DP-1] s[true], layoutopt:direction:up
workspace = m[DP-1] n[true], layoutopt:direction:up

