# ### PLUGINS ###
# === bunny ===
[[mgr.prepend_keymap]]
desc = "Start bunny.yazi"
on = ";"
run = "plugin bunny"
# Optionally, add another keymap to immediately fuzzy search bookmarks
[[mgr.prepend_keymap]]
desc = "Start bunny.yazi fuzzy search"
on = "'"
run = "plugin bunny fuzzy"

# === lazygit.yazi ===
[[mgr.prepend_keymap]]
on   = [ "g", "i" ]
run  = "plugin lazygit"
desc = "run lazygit"

# === projects.yazi === 
[[mgr.prepend_keymap]]
on = [ "P", "s" ]
run = "plugin projects save"
desc = "Save current project"

[[mgr.prepend_keymap]]
on = [ "P", "l" ]
run = "plugin projects load"
desc = "Load project"

[[mgr.prepend_keymap]]
on = [ "P", "P" ]
run = "plugin projects load_last"
desc = "Load last project"

[[mgr.prepend_keymap]]
on = [ "P", "d" ]
run = "plugin projects delete"
desc = "Delete project"

[[mgr.prepend_keymap]]
on = [ "P", "D" ]
run = "plugin projects delete_all"
desc = "Delete all projects"

[[mgr.prepend_keymap]]
on = [ "P", "m" ]
run = "plugin projects 'merge current'"
desc = "Merge current tab to other projects"

[[mgr.prepend_keymap]]
on = [ "P", "M" ]
run = "plugin projects 'merge all'"
desc = "Merge current project to other projects"

# === recycle-bin ===
[[mgr.prepend_keymap]]
desc = "Open Recycle Bin menu"
on = ["R", "b"]
run = "plugin recycle-bin"

# === mediainfo ===
[[mgr.prepend_keymap]]
desc = "Toggle media preview metadata"
on = "<F9>"
run = "plugin mediainfo -- toggle-metadata"

# === ouch ===
[[mgr.prepend_keymap]]
desc = "Compress with ouch"
on = ["C"]
run = "plugin ouch"

# === what-size ===
[[mgr.prepend_keymap]]
desc = "Calc size of selection or cwd"
on = [ "S", "s" ]
run  = "plugin what-size"

# === smart-paste ===
[[mgr.prepend_keymap]]
desc = "Paste into the hovered directory or CWD"
on   = "p"
run  = "plugin smart-paste"

# === confirm-quit.yazi ===
[[mgr.prepend_keymap]]
on  = "q"
run = "plugin confirm-quit"
